package in.voltforge.api.ai.service.impl;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import in.voltforge.api.ai.dto.*;
import in.voltforge.api.ai.service.AiService;
import in.voltforge.api.config.VoltforgeAiConfig;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.Duration;
import java.util.*;

/**
 * Delegates VoltForge AI requests to the standalone Python AI microservice.
 */
@Slf4j
@Service
public class AiServiceImpl implements AiService {

    private final WebClient voltforgeAiWebClient;
    private final VoltforgeAiConfig aiConfig;
    private final ObjectMapper objectMapper;

    public AiServiceImpl(@Qualifier("voltforgeAiWebClient") WebClient voltforgeAiWebClient,
                         VoltforgeAiConfig aiConfig,
                         ObjectMapper objectMapper) {
        this.voltforgeAiWebClient = voltforgeAiWebClient;
        this.aiConfig = aiConfig;
        this.objectMapper = objectMapper;
    }

    @Override
    public AiGenerateResponse generateCircuit(AiGenerateRequest request) {
        log.info("Delegating generateCircuit to VoltForge AI microservice");
        return callGenerateEndpoint("/api/v1/model/generate-code", request, "Circuit model generated by VoltForge AI.");
    }

    @Override
    public AiGenerateResponse suggestWiring(AiGenerateRequest request) {
        log.info("Delegating suggestWiring to VoltForge AI microservice");
        try {
            JsonNode data = post("/api/v1/model/suggest-wiring", buildGenerateBody(request));
            return AiGenerateResponse.builder()
                    .status(data.path("status").asText("SUCCESS"))
                    .message(data.path("message").asText("Wiring suggestions generated successfully."))
                    .wireSuggestions(parseWireSuggestions(data))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .confidence(readDouble(data, "confidence"))
                    .build();
        } catch (Exception e) {
            log.error("Error communicating with AI microservice: {}", e.getMessage(), e);
            return AiGenerateResponse.builder()
                    .status("ERROR")
                    .message("AI microservice error: " + e.getMessage())
                    .wireSuggestions(Collections.emptyList())
                    .build();
        }
    }

    @Override
    public AiGenerateResponse generateCode(AiGenerateRequest request) {
        log.info("Delegating generateCode to VoltForge AI microservice");
        return callGenerateEndpoint("/api/v1/model/generate-code", request, "Code generated successfully.");
    }

    @Override
    public AiChatResponse chat(AiChatRequest request) {
        log.info("Delegating chat to VoltForge AI microservice");
        try {
            List<Map<String, String>> history = new ArrayList<>();
            if (request.getHistory() != null) {
                for (var msg : request.getHistory()) {
                    history.add(Map.of(
                            "role", nullToEmpty(msg.getRole()),
                            "content", nullToEmpty(msg.getContent())
                    ));
                }
            }

            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("message", request.getMessage());
            requestBody.put("context", request.getContext() != null ? request.getContext() : "");
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("components", request.getComponents() != null ? request.getComponents() : Collections.emptyList());
            requestBody.put("wires", request.getWires() != null ? request.getWires() : Collections.emptyList());
            requestBody.put("netlist", request.getNetlist() != null ? request.getNetlist() : Collections.emptyMap());
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("canvasData", request.getCanvasData() != null ? request.getCanvasData() : Collections.emptyMap());
            requestBody.put("simulationState", request.getSimulationState() != null ? request.getSimulationState() : Collections.emptyMap());
            requestBody.put("history", history);

            JsonNode data = post("/api/v1/model/chat", requestBody);

            return AiChatResponse.builder()
                    .reply(data.path("reply").asText("Unable to process query."))
                    .generatedCode(readNullableText(data, "generatedCode"))
                    .hasCode(data.path("hasCode").asBoolean(false))
                    .confidence(readDouble(data, "confidence"))
                    .citations(readStringMapList(data, "citations"))
                    .wireSuggestions(parseWireSuggestions(data))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .valueChanges(readMapList(data, "valueChanges"))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .build();

        } catch (Exception e) {
            log.error("Error communicating with AI microservice: {}", e.getMessage(), e);
            return AiChatResponse.builder()
                    .reply("AI microservice is offline or encountered an error: " + e.getMessage())
                    .hasCode(false)
                    .confidence(0.0)
                    .citations(Collections.emptyList())
                    .wireSuggestions(Collections.emptyList())
                    .additions(Collections.emptyList())
                    .removals(Collections.emptyList())
                    .valueChanges(Collections.emptyList())
                    .codeFixes(Collections.emptyList())
                    .build();
        }
    }

    @Override
    public AiCodeReviewResponse reviewCode(AiCodeReviewRequest request) {
        log.info("Delegating reviewCode to VoltForge AI microservice");
        try {
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("componentTypes", request.getComponentTypes() != null ? request.getComponentTypes() : Collections.emptyList());
            requestBody.put("components", request.getComponents() != null ? request.getComponents() : Collections.emptyList());
            requestBody.put("wires", request.getWires() != null ? request.getWires() : Collections.emptyList());
            requestBody.put("circuitDescription", defaultString(request.getCircuitDescription(), ""));
            requestBody.put("compilerDiagnostics", request.getCompilerDiagnostics() != null ? request.getCompilerDiagnostics() : Collections.emptyList());

            JsonNode data = post("/api/v1/model/review-code", requestBody);
            return AiCodeReviewResponse.builder()
                    .summary(data.path("summary").asText("Code review completed."))
                    .issues(parseReviewIssues(data))
                    .suggestions(readStringList(data, "suggestions"))
                    .improvedCode(data.path("improvedCode").asText(defaultString(request.getCode(), "")))
                    .score(data.path("score").asInt(100))
                    .confidence(readDouble(data, "confidence"))
                    .build();
        } catch (Exception e) {
            log.error("Error communicating with AI microservice: {}", e.getMessage(), e);
            return AiCodeReviewResponse.builder()
                    .summary("AI code review is currently unavailable.")
                    .issues(Collections.emptyList())
                    .suggestions(List.of("Verify board compilation locally using the compile service."))
                    .improvedCode(request.getCode())
                    .score(0)
                    .confidence(0.0)
                    .build();
        }
    }

    @Override
    public AiGenerateResponse schematicToCode(AiSchematicToCodeRequest request) {
        log.info("Delegating schematicToCode to VoltForge AI microservice");
        try {
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("components", toMaps(request.getComponents()));
            requestBody.put("wires", toMaps(request.getWires()));
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("additionalInstructions", defaultString(request.getAdditionalInstructions(), ""));

            JsonNode data = post("/api/v1/model/schematic-to-code", requestBody);
            return AiGenerateResponse.builder()
                    .status(data.path("status").asText("SUCCESS"))
                    .message(data.path("message").asText("Code generated successfully from schematic layout."))
                    .generatedCode(data.path("generatedCode").asText(""))
                    .confidence(readDouble(data, "confidence"))
                    .citations(readStringMapList(data, "citations"))
                    .build();

        } catch (Exception e) {
            log.error("Error communicating with AI microservice: {}", e.getMessage(), e);
            return AiGenerateResponse.builder()
                    .status("ERROR")
                    .message("AI microservice error: " + e.getMessage())
                    .generatedCode(generateFallbackCode("schematicToCode"))
                    .confidence(0.0)
                    .build();
        }
    }

    @Override
    public AiValidatorResponse validateCircuit(AiValidatorRequest request) {
        log.info("Delegating validateCircuit to VoltForge AI microservice");
        try {
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("components", toMaps(request.getComponents()));
            requestBody.put("wires", toMaps(request.getWires()));
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("context", defaultString(request.getContext(), ""));
            requestBody.put("compilerDiagnostics", request.getCompilerDiagnostics() != null ? request.getCompilerDiagnostics() : Collections.emptyList());

            JsonNode data = post("/api/v1/model/validate-circuit", requestBody);

            return AiValidatorResponse.builder()
                    .isValid(data.path("isValid").asBoolean(true))
                    .safetyScore(data.path("safetyScore").asInt(100))
                    .issues(parseValidationIssues(data))
                    .generalFeedback(data.path("generalFeedback").asText(""))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .valueChanges(readMapList(data, "valueChanges"))
                    .wireSuggestions(parseWireSuggestions(data))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .confidence(readDouble(data, "confidence"))
                    .build();

        } catch (Exception e) {
            log.error("Error communicating with AI microservice: {}", e.getMessage(), e);
            return AiValidatorResponse.builder()
                    .isValid(false)
                    .safetyScore(0)
                    .issues(Collections.emptyList())
                    .generalFeedback("AI microservice is currently offline.")
                    .additions(Collections.emptyList())
                    .removals(Collections.emptyList())
                    .valueChanges(Collections.emptyList())
                    .wireSuggestions(Collections.emptyList())
                    .codeFixes(Collections.emptyList())
                    .confidence(0.0)
                    .build();
        }
    }

    private AiGenerateResponse callGenerateEndpoint(String uri, AiGenerateRequest request, String defaultMessage) {
        try {
            JsonNode data = post(uri, buildGenerateBody(request));
            return AiGenerateResponse.builder()
                    .status(data.path("status").asText("SUCCESS"))
                    .message(data.path("message").asText(defaultMessage))
                    .canvasLayout(readMap(data, "canvasLayout"))
                    .componentConfig(readMap(data, "componentConfig"))
                    .wireSuggestions(parseWireSuggestions(data))
                    .generatedCode(data.path("generatedCode").asText(""))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .citations(readStringMapList(data, "citations"))
                    .confidence(readDouble(data, "confidence"))
                    .build();
        } catch (Exception e) {
            log.error("Error communicating with AI microservice: {}", e.getMessage(), e);
            return AiGenerateResponse.builder()
                    .status("ERROR")
                    .message("AI microservice error: " + e.getMessage())
                    .generatedCode(generateFallbackCode(request != null ? request.getPrompt() : ""))
                    .confidence(0.0)
                    .build();
        }
    }

    private JsonNode post(String uri, Map<String, Object> requestBody) {
        JsonNode response = voltforgeAiWebClient.post()
                .uri(uri)
                .bodyValue(requestBody)
                .retrieve()
                .bodyToMono(JsonNode.class)
                .block(Duration.ofSeconds(aiConfig.getTimeoutSeconds()));
        return unwrapData(response);
    }

    private JsonNode unwrapData(JsonNode response) {
        if (response == null) {
            return objectMapper.createObjectNode();
        }
        if (response.has("data") && response.get("data").isObject()) {
            return response.get("data");
        }
        return response;
    }

    private Map<String, Object> buildGenerateBody(AiGenerateRequest request) {
        Map<String, Object> body = new LinkedHashMap<>();
        String boardType = request != null && request.getBoardType() != null ? request.getBoardType().name() : "ARDUINO_UNO";
        List<Map<String, Object>> components = request != null && request.getComponents() != null
                ? request.getComponents()
                : Collections.emptyList();
        if ((components == null || components.isEmpty()) && request != null) {
            components = parseComponentsFromPrompt(request.getPrompt());
        }

        body.put("boardType", boardType);
        body.put("prompt", request != null ? defaultString(request.getPrompt(), "") : "");
        body.put("components", components != null ? components : Collections.emptyList());
        body.put("wires", request != null && request.getWires() != null ? request.getWires() : Collections.emptyList());
        body.put("code", request != null ? defaultString(request.getCode(), "") : "");
        body.put("context", request != null ? defaultString(request.getContext(), "") : "");
        body.put("componentTypes", request != null && request.getComponentTypes() != null ? request.getComponentTypes() : Collections.emptyList());
        return body;
    }

    private List<AiWireSuggestion> parseWireSuggestions(JsonNode data) {
        JsonNode suggestionsNode = data.path("suggestions");
        if (!suggestionsNode.isArray()) {
            suggestionsNode = data.path("wireSuggestions");
        }
        if (!suggestionsNode.isArray()) {
            return Collections.emptyList();
        }
        List<AiWireSuggestion> suggestions = new ArrayList<>();
        for (JsonNode node : suggestionsNode) {
            suggestions.add(AiWireSuggestion.builder()
                    .fromComponentId(node.path("fromComponentId").asText())
                    .fromPin(node.path("fromPin").asText())
                    .toComponentId(node.path("toComponentId").asText())
                    .toPin(node.path("toPin").asText())
                    .color(node.path("color").asText("#3b82f6"))
                    .description(node.path("description").asText())
                    .build());
        }
        return suggestions;
    }

    private List<AiValidatorResponse.ValidationIssue> parseValidationIssues(JsonNode data) {
        JsonNode issuesNode = data.path("issues");
        if (!issuesNode.isArray()) {
            return Collections.emptyList();
        }
        List<AiValidatorResponse.ValidationIssue> issues = new ArrayList<>();
        for (JsonNode node : issuesNode) {
            issues.add(AiValidatorResponse.ValidationIssue.builder()
                    .severity(node.path("severity").asText("INFO"))
                    .componentId(node.path("componentId").asText(""))
                    .message(node.path("message").asText(""))
                    .suggestedFix(node.path("suggestedFix").asText(""))
                    .build());
        }
        return issues;
    }

    private List<AiCodeReviewResponse.ReviewIssue> parseReviewIssues(JsonNode data) {
        JsonNode issuesNode = data.path("issues");
        if (!issuesNode.isArray()) {
            return Collections.emptyList();
        }
        List<AiCodeReviewResponse.ReviewIssue> issues = new ArrayList<>();
        for (JsonNode node : issuesNode) {
            issues.add(AiCodeReviewResponse.ReviewIssue.builder()
                    .severity(node.path("severity").asText("INFO"))
                    .line(node.path("line").asInt(1))
                    .message(node.path("message").asText(""))
                    .fix(node.path("fix").asText(""))
                    .build());
        }
        return issues;
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> toMaps(Object value) {
        if (value == null) {
            return Collections.emptyList();
        }
        return objectMapper.convertValue(value, new TypeReference<List<Map<String, Object>>>() {});
    }

    private Map<String, Object> readMap(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isObject()) {
            return null;
        }
        return objectMapper.convertValue(node, new TypeReference<Map<String, Object>>() {});
    }

    private List<Map<String, Object>> readMapList(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isArray()) {
            return Collections.emptyList();
        }
        return objectMapper.convertValue(node, new TypeReference<List<Map<String, Object>>>() {});
    }

    private List<Map<String, String>> readStringMapList(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isArray()) {
            return Collections.emptyList();
        }
        return objectMapper.convertValue(node, new TypeReference<List<Map<String, String>>>() {});
    }

    private List<String> readStringList(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isArray()) {
            return Collections.emptyList();
        }
        List<String> values = new ArrayList<>();
        for (JsonNode item : node) {
            values.add(item.asText());
        }
        return values;
    }

    private Double readDouble(JsonNode data, String field) {
        JsonNode node = data.path(field);
        return node.isNumber() ? node.asDouble() : null;
    }

    private String readNullableText(JsonNode data, String field) {
        JsonNode node = data.get(field);
        return node == null || node.isNull() ? null : node.asText();
    }

    private String defaultString(String value, String fallback) {
        return value != null ? value : fallback;
    }

    private String nullToEmpty(String value) {
        return value != null ? value : "";
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> parseComponentsFromPrompt(String prompt) {
        List<Map<String, Object>> components = new ArrayList<>();
        if (prompt == null) return components;

        java.util.regex.Pattern compPattern = java.util.regex.Pattern.compile(
                "-\\s+([^:]+):\\s+(.+?)\\s+\\(([A-Z0-9_]+)\\)\\s+pins:\\s+(.+)",
                java.util.regex.Pattern.CASE_INSENSITIVE);

        for (String line : prompt.split("\\n")) {
            java.util.regex.Matcher matcher = compPattern.matcher(line.trim());
            if (!matcher.find()) {
                continue;
            }
            String compId = matcher.group(1).trim();
            String compName = matcher.group(2).trim();
            String compType = matcher.group(3).trim();
            String pinsStr = matcher.group(4).trim();

            List<Map<String, Object>> pins = new ArrayList<>();
            for (String pinEntry : pinsStr.split(",\\s*")) {
                String[] parts = pinEntry.trim().split("/", 2);
                if (parts.length >= 1) {
                    Map<String, Object> pin = new HashMap<>();
                    pin.put("id", parts[0].trim());
                    pin.put("name", parts.length > 1 ? parts[1].trim() : parts[0].trim());
                    pins.add(pin);
                }
            }

            Map<String, Object> comp = new HashMap<>();
            comp.put("id", compId);
            comp.put("name", compName);
            comp.put("type", compType);
            comp.put("pins", pins);
            components.add(comp);
        }
        return components;
    }

    private String generateFallbackCode(String prompt) {
        return "// VoltForge AI fallback code\n" +
                "#include <Arduino.h>\n\n" +
                "void setup() {\n" +
                "  Serial.begin(9600);\n" +
                "}\n\n" +
                "void loop() {\n" +
                "  delay(1000);\n" +
                "}\n";
    }
}
