package in.voltforge.api.ai.service.impl;

import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.node.ObjectNode;
import in.voltforge.api.ai.dto.*;
import in.voltforge.api.ai.gateway.AiGatewayException;
import in.voltforge.api.ai.gateway.AiGatewayPolicy;
import in.voltforge.api.ai.gateway.AiRequestAdmission;
import in.voltforge.api.ai.observability.AiTelemetry;
import in.voltforge.api.ai.service.AiService;
import in.voltforge.api.config.VoltforgeAiConfig;
import org.springframework.beans.factory.annotation.Autowired;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.Duration;
import java.nio.charset.StandardCharsets;
import java.util.*;

import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.codec.ServerSentEvent;
import reactor.core.publisher.Flux;
import reactor.core.publisher.SignalType;

/**
 * Delegates VoltForge AI requests to the standalone Python AI microservice.
 */
@Slf4j
@Service
public class AiServiceImpl implements AiService {

    private final WebClient voltforgeAiWebClient;
    private final WebClient voltforgeAiStreamingClient;
    private final VoltforgeAiConfig aiConfig;
    private final JsonMapper objectMapper;
    private final AiGatewayPolicy gatewayPolicy;
    private final AiRequestAdmission requestAdmission;
    private final AiTelemetry telemetry;

    @Autowired
    public AiServiceImpl(@Qualifier("voltforgeAiWebClient") WebClient voltforgeAiWebClient,
                         @Qualifier("voltforgeAiStreamingClient") WebClient voltforgeAiStreamingClient,
                         VoltforgeAiConfig aiConfig,
                         JsonMapper objectMapper,
                         AiGatewayPolicy gatewayPolicy,
                         AiRequestAdmission requestAdmission,
                         AiTelemetry telemetry) {
        this.voltforgeAiWebClient = voltforgeAiWebClient;
        this.voltforgeAiStreamingClient = voltforgeAiStreamingClient;
        this.aiConfig = aiConfig;
        this.objectMapper = objectMapper;
        this.gatewayPolicy = gatewayPolicy;
        this.requestAdmission = requestAdmission;
        this.telemetry = telemetry;
    }

    /** Compatibility constructor for focused tests with explicit gateway collaborators. */
    public AiServiceImpl(WebClient voltforgeAiWebClient,
                         WebClient voltforgeAiStreamingClient,
                         VoltforgeAiConfig aiConfig,
                         JsonMapper objectMapper,
                         AiGatewayPolicy gatewayPolicy,
                         AiRequestAdmission requestAdmission) {
        this(voltforgeAiWebClient, voltforgeAiStreamingClient, aiConfig, objectMapper,
                gatewayPolicy, requestAdmission, new AiTelemetry());
    }

    /** Compatibility constructor for focused unit tests and lightweight embedders. */
    public AiServiceImpl(WebClient voltforgeAiWebClient,
                         WebClient voltforgeAiStreamingClient,
                         VoltforgeAiConfig aiConfig,
                         JsonMapper objectMapper) {
        this(voltforgeAiWebClient, voltforgeAiStreamingClient, aiConfig, objectMapper,
                new AiGatewayPolicy(objectMapper, aiConfig), new AiRequestAdmission(aiConfig),
                new AiTelemetry());
    }

    @Override
    public AiGenerateResponse generateCircuit(AiGenerateRequest request) {
        log.info("Delegating generateCircuit to VoltForge AI microservice");
        return callGenerateEndpoint("/api/v1/model/generate-code", request, "Circuit model generated by VoltForge AI.");
    }

    @Override
    public AiGenerateResponse suggestWiring(AiGenerateRequest request) {
        log.info("Delegating suggestWiring to VoltForge AI microservice");
        try {
            JsonNode data = post("/api/v1/model/suggest-wiring", buildGenerateBody(request));
            return AiGenerateResponse.builder()
                    .status(data.path("status").asString("SUCCESS"))
                    .message(data.path("message").asString("Wiring suggestions generated successfully."))
                    .wireSuggestions(parseWireSuggestions(data))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .confidence(readDouble(data, "confidence"))
                    .build();
        } catch (Exception e) {
            log.error("AI suggestWiring request failed (errorType={})", e.getClass().getSimpleName());
            return AiGenerateResponse.builder()
                    .status("ERROR")
                    .message("VoltForge AI is temporarily unavailable. Please try again.")
                    .wireSuggestions(Collections.emptyList())
                    .build();
        }
    }

    @Override
    public AiGenerateResponse generateCode(AiGenerateRequest request) {
        log.info("Delegating generateCode to VoltForge AI microservice");
        return callGenerateEndpoint("/api/v1/model/generate-code", request, "Code generated successfully.");
    }

    @Override
    public AiChatResponse chat(AiChatRequest request) {
        log.info("Delegating chat to VoltForge AI microservice");
        gatewayPolicy.validateChatRequest(request);
        try {
            ensureChatSession(request);
            JsonNode data = postChat("/api/v1/model/chat", buildChatBody(request), request);

            return AiChatResponse.builder()
                    .schemaVersion(data.path("schemaVersion").asInt(1))
                    .contractVersion(data.path("contractVersion").asString("1.0.0"))
                    .requestId(readNullableText(data, "requestId"))
                    .sessionId(readNullableText(data, "sessionId"))
                    .projectRevision(readNullableText(data, "projectRevision"))
                    .model(readNullableText(data, "model"))
                    .mode(readNullableText(data, "mode"))
                    .artifact(readMap(data, "artifact"))
                    .readiness(readMap(data, "readiness"))
                    .reply(data.path("reply").asString("Unable to process query."))
                    .generatedCode(readNullableText(data, "generatedCode"))
                    .hasCode(data.path("hasCode").asBoolean(false))
                    .confidence(readDouble(data, "confidence"))
                    .citations(readMapList(data, "citations"))
                    .wireSuggestions(parseWireSuggestions(data))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .valueChanges(readMapList(data, "valueChanges"))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .engineeringAuthorityActive(data.path("engineeringAuthorityActive").isBoolean()
                            ? data.path("engineeringAuthorityActive").asBoolean() : null)
                    .engineeringAuthority(readMap(data, "engineeringAuthority"))
                    .engineeringFindings(readMapList(data, "engineeringFindings"))
                    .omittedEngineeringFindingCount(data.path("omittedEngineeringFindingCount").isInt()
                            ? data.path("omittedEngineeringFindingCount").asInt() : null)
                    .localRetrieval(readMap(data, "localRetrieval"))
                    .internetRetrieval(readMap(data, "internetRetrieval"))
                    .grounding(readMap(data, "grounding"))
                    .memory(readMap(data, "memory"))
                    .build();

        } catch (Exception e) {
            log.error("AI chat request failed (errorType={})", e.getClass().getSimpleName());
            return AiChatResponse.builder()
                    .reply("VoltForge AI is temporarily unavailable. Your project was not changed.")
                    .sessionId(request.getSessionId())
                    .projectRevision(request.getProjectRevision())
                    .hasCode(false)
                    .confidence(0.0)
                    .citations(Collections.emptyList())
                    .wireSuggestions(Collections.emptyList())
                    .additions(Collections.emptyList())
                    .removals(Collections.emptyList())
                    .valueChanges(Collections.emptyList())
                    .codeFixes(Collections.emptyList())
                    .build();
        }
    }

    @Override
    public Flux<ServerSentEvent<String>> chatStream(AiChatRequest request) {
        log.info("Delegating streaming chat to VoltForge AI microservice");
        ensureChatSession(request);
        String requestId = "gateway-" + UUID.randomUUID();
        return Flux.defer(() -> {
            AiTelemetry.Observation observation = telemetry.start("chat.stream");
            AiRequestAdmission.Lease lease = null;
            try {
                gatewayPolicy.validateChatRequest(request);
                AiRequestAdmission.Lease acquiredLease = requestAdmission.acquireStreaming(
                        request.getAuthenticatedUserId(), request.getProjectId());
                lease = acquiredLease;
                Map<String, Object> requestBody = buildChatBody(request);
                WebClient.RequestBodySpec requestSpec = voltforgeAiStreamingClient.post()
                        .uri("/api/v1/model/chat/stream")
                        .header("X-Voltforge-Request-Id", requestId)
                        .contentType(MediaType.APPLICATION_JSON);
                addMemoryIdentityHeaders(requestSpec, request.getAuthenticatedUserId(),
                        request.getProjectId(), request.getSessionId());
                return requestSpec
                        .bodyValue(requestBody)
                        .accept(MediaType.TEXT_EVENT_STREAM)
                        .retrieve()
                        // bodyToFlux is deliberately returned directly. Reactor
                        // cancellation closes the upstream HTTP response.
                        .bodyToFlux(new ParameterizedTypeReference<ServerSentEvent<String>>() {})
                        .doOnNext(event -> telemetry.observeStreamEvent(
                                observation,
                                event.event(),
                                event.data() == null ? 0 : event.data().getBytes(StandardCharsets.UTF_8).length))
                        .doOnCancel(() -> {
                            telemetry.finish(observation, "cancelled");
                            log.debug("AI stream cancelled by gateway client (requestId={})", requestId);
                        })
                        .doFinally(signal -> {
                            telemetry.finish(observation, streamOutcome(signal));
                            acquiredLease.close();
                        })
                        .onErrorResume(error -> {
                            log.error("AI streaming request failed (requestId={}, errorType={})",
                                    requestId, error.getClass().getSimpleName());
                            return Flux.just(gatewayErrorEvent(request, requestId, error));
                        });
            } catch (RuntimeException error) {
                if (lease != null) {
                    lease.close();
                }
                telemetry.finish(observation,
                        error instanceof AiGatewayException gatewayError
                                && gatewayError.getStatus() == org.springframework.http.HttpStatus.TOO_MANY_REQUESTS
                                ? "rejected" : "failure");
                return Flux.just(gatewayErrorEvent(request, requestId, error));
            }
        }).onErrorResume(error -> Flux.just(gatewayErrorEvent(request, requestId, error)));
    }

    private String streamOutcome(SignalType signal) {
        if (signal == SignalType.CANCEL) {
            return "cancelled";
        }
        if (signal == SignalType.ON_ERROR) {
            return "failure";
        }
        return "success";
    }

    private ServerSentEvent<String> gatewayErrorEvent(AiChatRequest request, String requestId, Throwable error) {
        String code = "AI_GATEWAY_STREAM_FAILED";
        String message = "The VoltForge AI response could not continue.";
        boolean retryable = true;
        if (error instanceof AiGatewayException gatewayError) {
            code = gatewayError.getErrorCode();
            message = gatewayError.getMessage();
            retryable = gatewayError.isRetryable();
        }

        ObjectNode payload = objectMapper.createObjectNode();
        payload.put("schemaVersion", 1);
        payload.put("contractVersion", "1.0.0");
        payload.put("type", "error");
        payload.put("eventId", "event:v1:" + requestId + ":0");
        payload.put("sequence", 0);
        payload.put("requestId", requestId);
        payload.put("sessionId", contractToken(request != null ? request.getSessionId() : null, "session:unknown"));
        payload.put("projectRevision", contractToken(request != null ? request.getProjectRevision() : null, "client:unbound"));
        payload.put("model", "voltforge-local-engine-v1");
        payload.put("mode", "unavailable");
        ObjectNode artifact = payload.putObject("artifact");
        artifact.put("artifactVersion", "gateway-unavailable-v1");
        artifact.put("runtimeState", "unavailable");
        artifact.put("ready", false);

        ObjectNode eventPayload = payload.putObject("payload");
        eventPayload.put("type", "error");
        eventPayload.put("code", code);
        eventPayload.put("message", message);
        eventPayload.put("retryable", retryable);
        // Keep the temporary flat shape consumed by older UI clients.
        payload.put("code", code);
        payload.put("message", message);
        payload.put("retryable", retryable);
        return ServerSentEvent.<String>builder(payload.toString()).event("error").build();
    }

    private String contractToken(String value, String fallback) {
        if (value == null || value.isBlank()) {
            return fallback;
        }
        String token = value.replaceAll("[^A-Za-z0-9._:@/+\\-]", "_");
        return token.length() >= 3 ? token.substring(0, Math.min(token.length(), 160)) : fallback;
    }

    private Map<String, Object> buildChatBody(AiChatRequest request) {
        List<Map<String, String>> history = new ArrayList<>();
        if (request.getHistory() != null) {
            for (var msg : request.getHistory()) {
                history.add(Map.of(
                        "role", nullToEmpty(msg.getRole()),
                        "content", nullToEmpty(msg.getContent())
                ));
            }
        }
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("schemaVersion", 1);
        body.put("contractVersion", "1.0.0");
        body.put("message", request.getMessage());
        body.put("sessionId", request.getSessionId());
        body.put("projectId", request.getProjectId());
        body.put("projectRevision", request.getProjectRevision());
        body.put("context", request.getContext() != null ? request.getContext() : "");
        body.put("canvasContext", request.getCanvasContext() != null ? request.getCanvasContext() : "");
        body.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
        body.put("components", request.getComponents() != null ? request.getComponents() : Collections.emptyList());
        body.put("wires", request.getWires() != null ? request.getWires() : Collections.emptyList());
        body.put("netlist", request.getNetlist() != null ? request.getNetlist() : Collections.emptyMap());
        body.put("code", defaultString(request.getCode(), ""));
        body.put("canvasData", request.getCanvasData() != null ? request.getCanvasData() : Collections.emptyMap());
        body.put("simulationState", request.getSimulationState() != null ? request.getSimulationState() : Collections.emptyMap());
        body.put("history", history);
        body.put("files", request.getFiles() != null ? request.getFiles() : Collections.emptyList());
        body.put("diagnostics", request.getDiagnostics() != null ? request.getDiagnostics() : Collections.emptyList());
        // Browser/client memory is never trusted. The Python service loads only
        // entries bound to the authenticated identity headers below.
        body.put("memory", Collections.emptyList());
        body.put("retrievedEvidence", request.getRetrievedEvidence() != null ? request.getRetrievedEvidence() : Collections.emptyList());
        return body;
    }

    @Override
    public Map<String, Object> inspectMemory(String userId, String projectId, String sessionId, String projectRevision) {
        String uri = "/api/v1/model/memory";
        if (projectRevision != null && !projectRevision.isBlank()) {
            uri += "?projectRevision=" + encodeQuery(projectRevision);
        }
        return memoryRequest(HttpMethod.GET, uri, null, userId, projectId, sessionId);
    }

    @Override
    public Map<String, Object> setMemoryPreference(String userId, String projectId, String sessionId,
                                                    AiMemoryPreferenceRequest request) {
        return memoryRequest(HttpMethod.PUT, "/api/v1/model/memory/preferences",
                objectMapper.convertValue(request, new TypeReference<Map<String, Object>>() {}),
                userId, projectId, sessionId);
    }

    @Override
    public Map<String, Object> createMemoryEntry(String userId, String projectId, String sessionId,
                                                 AiMemoryWriteRequest request) {
        return memoryRequest(HttpMethod.POST, "/api/v1/model/memory/entries",
                objectMapper.convertValue(request, new TypeReference<Map<String, Object>>() {}),
                userId, projectId, sessionId);
    }

    @Override
    public Map<String, Object> correctMemoryEntry(String userId, String projectId, String sessionId,
                                                  String memoryId, AiMemoryCorrectionRequest request) {
        return memoryRequest(HttpMethod.PATCH, "/api/v1/model/memory/entries/" + encodePath(memoryId),
                objectMapper.convertValue(request, new TypeReference<Map<String, Object>>() {}),
                userId, projectId, sessionId);
    }

    @Override
    public Map<String, Object> deleteMemoryEntry(String userId, String projectId, String sessionId,
                                                 String memoryId) {
        return memoryRequest(HttpMethod.DELETE, "/api/v1/model/memory/entries/" + encodePath(memoryId),
                null, userId, projectId, sessionId);
    }

    @Override
    public Map<String, Object> clearMemory(String userId, String projectId, String sessionId, String scope) {
        return memoryRequest(HttpMethod.DELETE, "/api/v1/model/memory?scope=" + encodeQuery(scope),
                null, userId, projectId, sessionId);
    }

    @Override
    public AiCodeReviewResponse reviewCode(AiCodeReviewRequest request) {
        log.info("Delegating reviewCode to VoltForge AI microservice");
        try {
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("componentTypes", request.getComponentTypes() != null ? request.getComponentTypes() : Collections.emptyList());
            requestBody.put("components", request.getComponents() != null ? request.getComponents() : Collections.emptyList());
            requestBody.put("wires", request.getWires() != null ? request.getWires() : Collections.emptyList());
            requestBody.put("circuitDescription", defaultString(request.getCircuitDescription(), ""));
            requestBody.put("compilerDiagnostics", request.getCompilerDiagnostics() != null ? request.getCompilerDiagnostics() : Collections.emptyList());

            JsonNode data = post("/api/v1/model/review-code", requestBody);
            return AiCodeReviewResponse.builder()
                    .summary(data.path("summary").asString("Code review completed."))
                    .issues(parseReviewIssues(data))
                    .suggestions(readStringList(data, "suggestions"))
                    .improvedCode(data.path("improvedCode").asString(defaultString(request.getCode(), "")))
                    .score(data.path("score").asInt(100))
                    .confidence(readDouble(data, "confidence"))
                    .build();
        } catch (Exception e) {
            log.error("AI code-review request failed (errorType={})", e.getClass().getSimpleName());
            return AiCodeReviewResponse.builder()
                    .summary("AI code review is currently unavailable.")
                    .issues(Collections.emptyList())
                    .suggestions(List.of("Verify board compilation locally using the compile service."))
                    .improvedCode(request.getCode())
                    .score(0)
                    .confidence(0.0)
                    .build();
        }
    }

    @Override
    public AiGenerateResponse schematicToCode(AiSchematicToCodeRequest request) {
        log.info("Delegating schematicToCode to VoltForge AI microservice");
        try {
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("components", toMaps(request.getComponents()));
            requestBody.put("wires", toMaps(request.getWires()));
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("additionalInstructions", defaultString(request.getAdditionalInstructions(), ""));

            JsonNode data = post("/api/v1/model/schematic-to-code", requestBody);
            return AiGenerateResponse.builder()
                    .status(data.path("status").asString("SUCCESS"))
                    .message(data.path("message").asString("Code generated successfully from schematic layout."))
                    .generatedCode(data.path("generatedCode").asString(""))
                    .confidence(readDouble(data, "confidence"))
                    .citations(readStringMapList(data, "citations"))
                    .build();

        } catch (Exception e) {
            log.error("AI schematic-to-code request failed (errorType={})", e.getClass().getSimpleName());
            return AiGenerateResponse.builder()
                    .status("ERROR")
                    .message("VoltForge AI is temporarily unavailable. Please try again.")
                    .generatedCode(generateFallbackCode("schematicToCode"))
                    .confidence(0.0)
                    .build();
        }
    }

    @Override
    public AiValidatorResponse validateCircuit(AiValidatorRequest request) {
        log.info("Delegating validateCircuit to VoltForge AI microservice");
        try {
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("components", toMaps(request.getComponents()));
            requestBody.put("wires", toMaps(request.getWires()));
            requestBody.put("boardType", defaultString(request.getBoardType(), "ARDUINO_UNO"));
            requestBody.put("code", defaultString(request.getCode(), ""));
            requestBody.put("context", defaultString(request.getContext(), ""));
            requestBody.put("compilerDiagnostics", request.getCompilerDiagnostics() != null ? request.getCompilerDiagnostics() : Collections.emptyList());

            JsonNode data = post("/api/v1/model/validate-circuit", requestBody);

            return AiValidatorResponse.builder()
                    .isValid(data.path("isValid").asBoolean(true))
                    .safetyScore(data.path("safetyScore").asInt(100))
                    .issues(parseValidationIssues(data))
                    .generalFeedback(data.path("generalFeedback").asString(""))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .valueChanges(readMapList(data, "valueChanges"))
                    .wireSuggestions(parseWireSuggestions(data))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .confidence(readDouble(data, "confidence"))
                    .build();

        } catch (Exception e) {
            log.error("AI circuit-validation request failed (errorType={})", e.getClass().getSimpleName());
            return AiValidatorResponse.builder()
                    .isValid(false)
                    .safetyScore(0)
                    .issues(Collections.emptyList())
                    .generalFeedback("AI microservice is currently offline.")
                    .additions(Collections.emptyList())
                    .removals(Collections.emptyList())
                    .valueChanges(Collections.emptyList())
                    .wireSuggestions(Collections.emptyList())
                    .codeFixes(Collections.emptyList())
                    .confidence(0.0)
                    .build();
        }
    }

    @Override
    public Map<String, Object> getHardwareCoverage() {
        JsonNode data = get("/api/v1/model/hardware-coverage");
        return objectMapper.convertValue(data, new TypeReference<Map<String, Object>>() {});
    }

    @Override
    public Map<String, Object> getComponentCoverage() {
        JsonNode data = get("/api/v1/model/component-coverage");
        return objectMapper.convertValue(data, new TypeReference<Map<String, Object>>() {});
    }

    @Override
    public Map<String, Object> runPcbDrc(PcbManufacturingRequest request) {
        log.info("Delegating PCB DRC to VoltForge AI microservice");
        try {
            JsonNode data = post("/api/v1/model/circuit/drc-check", buildPcbManufacturingBody(request));
            return objectMapper.convertValue(data, new TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            log.error("AI PCB DRC request failed (errorType={})", e.getClass().getSimpleName());
            Map<String, Object> fallback = new LinkedHashMap<>();
            fallback.put("passed", false);
            fallback.put("totalViolations", 1);
            fallback.put("errors", 1);
            fallback.put("warnings", 0);
            fallback.put("violations", List.of(Map.of(
                    "id", "drc_service_unavailable",
                    "severity", "ERROR",
                    "rule", "DRC service availability",
                    "message", "PCB DRC service is unavailable. Please try again."
            )));
            fallback.put("rulesChecked", Collections.emptyList());
            return fallback;
        }
    }

    @Override
    public byte[] exportPcbGerber(PcbManufacturingRequest request) {
        log.info("Delegating PCB Gerber export to VoltForge AI microservice");
        AiTelemetry.Observation observation = telemetry.start("gerber");
        try {
            byte[] response = voltforgeAiWebClient.post()
                    .uri("/api/v1/model/circuit/export-gerber")
                    .contentType(MediaType.APPLICATION_JSON)
                    .bodyValue(buildPcbManufacturingBody(request))
                    .retrieve()
                    .bodyToMono(byte[].class)
                    .block(Duration.ofSeconds(aiConfig.getTimeoutSeconds()));
            telemetry.finish(observation, "success");
            return response != null ? response : new byte[0];
        } catch (RuntimeException error) {
            telemetry.finish(observation, telemetryOutcome(error));
            throw error;
        }
    }

    private AiGenerateResponse callGenerateEndpoint(String uri, AiGenerateRequest request, String defaultMessage) {
        try {
            JsonNode data = post(uri, buildGenerateBody(request));
            return AiGenerateResponse.builder()
                    .status(data.path("status").asString("SUCCESS"))
                    .message(data.path("message").asString(defaultMessage))
                    .canvasLayout(readMap(data, "canvasLayout"))
                    .componentConfig(readMap(data, "componentConfig"))
                    .wireSuggestions(parseWireSuggestions(data))
                    .generatedCode(data.path("generatedCode").asString(""))
                    .additions(readMapList(data, "additions"))
                    .removals(readMapList(data, "removals"))
                    .codeFixes(readMapList(data, "codeFixes"))
                    .citations(readStringMapList(data, "citations"))
                    .confidence(readDouble(data, "confidence"))
                    .build();
        } catch (Exception e) {
            log.error("AI generation request failed (errorType={})", e.getClass().getSimpleName());
            return AiGenerateResponse.builder()
                    .status("ERROR")
                    .message("VoltForge AI is temporarily unavailable. Please try again.")
                    .generatedCode(generateFallbackCode(request != null ? request.getPrompt() : ""))
                    .confidence(0.0)
                    .build();
        }
    }

    private JsonNode post(String uri, Map<String, Object> requestBody) {
        AiTelemetry.Observation observation = telemetry.start(operationForUri(uri));
        try {
            JsonNode response = voltforgeAiWebClient.post()
                    .uri(uri)
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(JsonNode.class)
                    .block(Duration.ofSeconds(aiConfig.getTimeoutSeconds()));
            telemetry.finish(observation, "success");
            return unwrapData(response);
        } catch (RuntimeException error) {
            telemetry.finish(observation, telemetryOutcome(error));
            throw error;
        }
    }

    private JsonNode get(String uri) {
        AiTelemetry.Observation observation = telemetry.start(operationForUri(uri));
        try {
            JsonNode response = voltforgeAiWebClient.get()
                    .uri(uri)
                    .retrieve()
                    .bodyToMono(JsonNode.class)
                    .block(Duration.ofSeconds(aiConfig.getTimeoutSeconds()));
            telemetry.finish(observation, "success");
            return unwrapData(response);
        } catch (RuntimeException error) {
            telemetry.finish(observation, telemetryOutcome(error));
            throw error;
        }
    }

    private JsonNode postChat(String uri, Map<String, Object> requestBody, AiChatRequest request) {
        AiTelemetry.Observation observation = telemetry.start("chat.sync");
        try {
            WebClient.RequestBodySpec requestSpec = voltforgeAiWebClient.post().uri(uri);
            addMemoryIdentityHeaders(requestSpec, request.getAuthenticatedUserId(),
                    request.getProjectId(), request.getSessionId());
            JsonNode response = requestSpec
                    .contentType(MediaType.APPLICATION_JSON)
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(JsonNode.class)
                    .block(Duration.ofSeconds(aiConfig.getTimeoutSeconds()));
            telemetry.finish(observation, "success");
            return unwrapData(response);
        } catch (RuntimeException error) {
            telemetry.finish(observation, telemetryOutcome(error));
            throw error;
        }
    }

    private String operationForUri(String uri) {
        if (uri == null) {
            return "other";
        }
        if (uri.contains("review-code")) return "review";
        if (uri.contains("validate-circuit")) return "validation";
        if (uri.contains("schematic-to-code")) return "schematic";
        if (uri.contains("drc-check")) return "drc";
        if (uri.contains("hardware-coverage")) return "hardware-coverage";
        if (uri.contains("component-coverage")) return "component-coverage";
        if (uri.contains("generate-code") || uri.contains("suggest-wiring")) return "generation";
        return "other";
    }

    private String telemetryOutcome(Throwable error) {
        if (error instanceof java.util.concurrent.TimeoutException
                || error.getClass().getSimpleName().toLowerCase(Locale.ROOT).contains("timeout")) {
            return "timeout";
        }
        if (error instanceof AiGatewayException gatewayError
                && gatewayError.getStatus() == org.springframework.http.HttpStatus.TOO_MANY_REQUESTS) {
            return "rejected";
        }
        return "failure";
    }

    private Map<String, Object> memoryRequest(HttpMethod method, String uri,
                                               Map<String, Object> body,
                                               String userId, String projectId, String sessionId) {
        WebClient.RequestBodySpec requestSpec = voltforgeAiWebClient.method(method).uri(uri);
        addMemoryIdentityHeaders(requestSpec, userId, projectId, sessionId);
        WebClient.RequestHeadersSpec<?> prepared = body == null
                ? requestSpec
                : requestSpec.contentType(MediaType.APPLICATION_JSON).bodyValue(body);
        JsonNode response = prepared.retrieve()
                .bodyToMono(JsonNode.class)
                .block(Duration.ofSeconds(aiConfig.getTimeoutSeconds()));
        JsonNode value = unwrapData(response);
        return objectMapper.convertValue(value, new TypeReference<Map<String, Object>>() {});
    }

    private void addMemoryIdentityHeaders(WebClient.RequestHeadersSpec<?> request,
                                          String userId, String projectId, String sessionId) {
        if (userId != null && !userId.isBlank()) request.header("X-Voltforge-User-Id", userId);
        if (projectId != null && !projectId.isBlank()) request.header("X-Voltforge-Project-Id", projectId);
        if (sessionId != null && !sessionId.isBlank()) request.header("X-Voltforge-Session-Id", sessionId);
    }

    private void ensureChatSession(AiChatRequest request) {
        if (request.getSessionId() == null || request.getSessionId().isBlank()) {
            request.setSessionId(UUID.randomUUID().toString());
        }
    }

    private String encodeQuery(String value) {
        return java.net.URLEncoder.encode(value, java.nio.charset.StandardCharsets.UTF_8);
    }

    private String encodePath(String value) {
        return value.replaceAll("[^A-Za-z0-9._:-]", "");
    }

    private JsonNode unwrapData(JsonNode response) {
        if (response == null) {
            return objectMapper.createObjectNode();
        }
        if (response.has("data") && response.get("data").isObject()) {
            return response.get("data");
        }
        return response;
    }

    private Map<String, Object> buildGenerateBody(AiGenerateRequest request) {
        Map<String, Object> body = new LinkedHashMap<>();
        String boardType = request != null && request.getBoardType() != null ? request.getBoardType().name() : "ARDUINO_UNO";
        List<Map<String, Object>> components = request != null && request.getComponents() != null
                ? request.getComponents()
                : Collections.emptyList();
        if ((components == null || components.isEmpty()) && request != null) {
            components = parseComponentsFromPrompt(request.getPrompt());
        }

        body.put("boardType", boardType);
        body.put("prompt", request != null ? defaultString(request.getPrompt(), "") : "");
        body.put("components", components != null ? components : Collections.emptyList());
        body.put("wires", request != null && request.getWires() != null ? request.getWires() : Collections.emptyList());
        body.put("code", request != null ? defaultString(request.getCode(), "") : "");
        body.put("context", request != null ? defaultString(request.getContext(), "") : "");
        body.put("componentTypes", request != null && request.getComponentTypes() != null ? request.getComponentTypes() : Collections.emptyList());
        return body;
    }

    private Map<String, Object> buildPcbManufacturingBody(PcbManufacturingRequest request) {
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("boardWidth_mm", request != null && request.getBoardWidthMm() != null ? request.getBoardWidthMm() : 100.0);
        body.put("boardHeight_mm", request != null && request.getBoardHeightMm() != null ? request.getBoardHeightMm() : 80.0);
        body.put("footprints", request != null && request.getFootprints() != null ? request.getFootprints() : Collections.emptyList());
        body.put("traces", request != null && request.getTraces() != null ? request.getTraces() : Collections.emptyList());
        body.put("vias", request != null && request.getVias() != null ? request.getVias() : Collections.emptyList());
        body.put("wires", request != null && request.getWires() != null ? request.getWires() : Collections.emptyList());
        body.put("projectName", sanitizeProjectName(request != null ? request.getProjectName() : null));
        return body;
    }

    private String sanitizeProjectName(String value) {
        String name = value != null && !value.isBlank() ? value : "VoltForge_PCB";
        return name.replaceAll("[^A-Za-z0-9_.-]", "_");
    }

    private List<AiWireSuggestion> parseWireSuggestions(JsonNode data) {
        JsonNode suggestionsNode = data.path("suggestions");
        if (!suggestionsNode.isArray()) {
            suggestionsNode = data.path("wireSuggestions");
        }
        if (!suggestionsNode.isArray()) {
            return Collections.emptyList();
        }
        List<AiWireSuggestion> suggestions = new ArrayList<>();
        for (JsonNode node : suggestionsNode) {
            suggestions.add(AiWireSuggestion.builder()
                    .fromComponentId(node.path("fromComponentId").asString())
                    .fromPin(node.path("fromPin").asString())
                    .toComponentId(node.path("toComponentId").asString())
                    .toPin(node.path("toPin").asString())
                    .color(node.path("color").asString("#3b82f6"))
                    .description(node.path("description").asString())
                    .build());
        }
        return suggestions;
    }

    private List<AiValidatorResponse.ValidationIssue> parseValidationIssues(JsonNode data) {
        JsonNode issuesNode = data.path("issues");
        if (!issuesNode.isArray()) {
            return Collections.emptyList();
        }
        List<AiValidatorResponse.ValidationIssue> issues = new ArrayList<>();
        for (JsonNode node : issuesNode) {
            issues.add(AiValidatorResponse.ValidationIssue.builder()
                    .severity(node.path("severity").asString("INFO"))
                    .componentId(node.path("componentId").asString(""))
                    .message(node.path("message").asString(""))
                    .suggestedFix(node.path("suggestedFix").asString(""))
                    .build());
        }
        return issues;
    }

    private List<AiCodeReviewResponse.ReviewIssue> parseReviewIssues(JsonNode data) {
        JsonNode issuesNode = data.path("issues");
        if (!issuesNode.isArray()) {
            return Collections.emptyList();
        }
        List<AiCodeReviewResponse.ReviewIssue> issues = new ArrayList<>();
        for (JsonNode node : issuesNode) {
            issues.add(AiCodeReviewResponse.ReviewIssue.builder()
                    .severity(node.path("severity").asString("INFO"))
                    .line(node.path("line").asInt(1))
                    .message(node.path("message").asString(""))
                    .fix(node.path("fix").asString(""))
                    .build());
        }
        return issues;
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> toMaps(Object value) {
        if (value == null) {
            return Collections.emptyList();
        }
        return objectMapper.convertValue(value, new TypeReference<List<Map<String, Object>>>() {});
    }

    private Map<String, Object> readMap(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isObject()) {
            return null;
        }
        return objectMapper.convertValue(node, new TypeReference<Map<String, Object>>() {});
    }

    private List<Map<String, Object>> readMapList(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isArray()) {
            return Collections.emptyList();
        }
        return objectMapper.convertValue(node, new TypeReference<List<Map<String, Object>>>() {});
    }

    private List<Map<String, String>> readStringMapList(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isArray()) {
            return Collections.emptyList();
        }
        return objectMapper.convertValue(node, new TypeReference<List<Map<String, String>>>() {});
    }

    private List<String> readStringList(JsonNode data, String field) {
        JsonNode node = data.path(field);
        if (!node.isArray()) {
            return Collections.emptyList();
        }
        List<String> values = new ArrayList<>();
        for (JsonNode item : node) {
            values.add(item.asString());
        }
        return values;
    }

    private Double readDouble(JsonNode data, String field) {
        JsonNode node = data.path(field);
        return node.isNumber() ? node.asDouble() : null;
    }

    private String readNullableText(JsonNode data, String field) {
        JsonNode node = data.get(field);
        return node == null || node.isNull() ? null : node.asString();
    }

    private String defaultString(String value, String fallback) {
        return value != null ? value : fallback;
    }

    private String nullToEmpty(String value) {
        return value != null ? value : "";
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> parseComponentsFromPrompt(String prompt) {
        List<Map<String, Object>> components = new ArrayList<>();
        if (prompt == null) return components;

        java.util.regex.Pattern compPattern = java.util.regex.Pattern.compile(
                "-\\s+([^:]+):\\s+(.+?)\\s+\\(([A-Z0-9_]+)\\)\\s+pins:\\s+(.+)",
                java.util.regex.Pattern.CASE_INSENSITIVE);

        for (String line : prompt.split("\\n")) {
            java.util.regex.Matcher matcher = compPattern.matcher(line.trim());
            if (!matcher.find()) {
                continue;
            }
            String compId = matcher.group(1).trim();
            String compName = matcher.group(2).trim();
            String compType = matcher.group(3).trim();
            String pinsStr = matcher.group(4).trim();

            List<Map<String, Object>> pins = new ArrayList<>();
            for (String pinEntry : pinsStr.split(",\\s*")) {
                String[] parts = pinEntry.trim().split("/", 2);
                if (parts.length >= 1) {
                    Map<String, Object> pin = new HashMap<>();
                    pin.put("id", parts[0].trim());
                    pin.put("name", parts.length > 1 ? parts[1].trim() : parts[0].trim());
                    pins.add(pin);
                }
            }

            Map<String, Object> comp = new HashMap<>();
            comp.put("id", compId);
            comp.put("name", compName);
            comp.put("type", compType);
            comp.put("pins", pins);
            components.add(comp);
        }
        return components;
    }

    private String generateFallbackCode(String prompt) {
        return "// VoltForge AI fallback code\n" +
                "#include <Arduino.h>\n\n" +
                "void setup() {\n" +
                "  Serial.begin(9600);\n" +
                "}\n\n" +
                "void loop() {\n" +
                "  delay(1000);\n" +
                "}\n";
    }
}
